FROM jenkins/jenkins:lts-jdk17

USER root

# Install Node.js, Docker CLI, kubectl, unzip, git
RUN apt-get update && \
    apt-get install -y curl git sudo unzip build-essential gnupg2 lsb-release && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && mv kubectl /usr/local/bin/ && \
    curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-24.0.2.tgz | tar -xzC /usr/local/bin --strip-components=1 docker/docker

# Switch back to jenkins user
USER jenkins