apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
        - name: backend
          image: news-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: api-secrets