server:
  port: ${PORT:8080}

spring:
  jackson:
    serialization:
      indent_output: true
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

guardian:
  api:
    key: ${GUARDIAN_API_KEY:}

nyt:
  api:
    key: ${NYT_API_KEY:}

news:
  guardian:
    enabled: true
  nyt:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    feign:
      Logger: DEBUG